#index:
#    path: /
#    controller: App\Controller\DefaultController::index


image_display:
    path: /image/{id}
    controller: App\Controller\ImageController::display

login:
    path: /login
    controller: App\Controller\LoginSignupController::login

logout:
    path: /logout