#index:
#    path: /
#    controller: App\Controller\DefaultController::index

addParticipation:
    path: /evenement/{id}/addparticipation
    controller: App\Controller\EvenementController::addParticipation